sudo: false
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx
env:
  - BUNDLE_WITHOUT=secondary
  - BUNDLE_WITHOUT=primary

matrix:
  include:
    - rvm: 1.9.3
      env: RDOC_VERSION="~>3.0"
  allow_failures:
    - rvm: rbx
    - env: BUNDLE_WITHOUT=primary
